version: '2'
services:
    nginx:
        image: qcacher/nginx
        build: nginx
        links:
            - "unbound:qcacher-dns"
        volumes:
            - cache-data:/srv
        ports:
            - 0.0.0.0:80:80/tcp
            - 0.0.0.0:443:443/tcp
            - 0.0.0.0:443:443/udp
    unbound:
        image: qcacher/unbound
        build: unbound
        ports:
            - 0.0.0.0:53:53/udp
        environment:
            CACHE_IP: 192.168.86.183
            CACHE_SUBNET: 192.168.0.0/16
volumes:
    cache-data:
        driver: local
