version: '2'
services:
    nginx:
        build: nginx
        volumes:
            - cache-data:/srv
        ports:
            - 0.0.0.0:80:80
    unbound:
        build: unbound
        ports:
            - 0.0.0.0:53:53/udp
        environment:
            DNS_IP: 192.168.86.183
    sniproxy:
        build: sniproxy
        ports:
            - 0.0.0.0:443:443
volumes:
    cache-data:
        driver: local
